In [1]:
import sys
import pandas as pd
import numpy as np
import requests

print("Python:", sys.version)
print("Python executable:", sys.executable)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Requests:", requests.__version__)

Python: 3.11.16 | packaged by Anaconda, Inc. | (main, Aug 27 2026, 14:36:16) [MSC v.1942 64 bit (AMD64)]
Python executable: c:\Users\MSI\.conda\envs\healthcare-de\python.exe
Pandas: 3.0.6
NumPy: 2.4.6
Requests: 2.34.2

In [2]:
import sys
import pandas as pd
import numpy as np

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.11.16 | packaged by Anaconda, Inc. | (main, Aug 27 2026, 14:36:16) [MSC v.1942 64 bit (AMD64)]
Pandas: 3.0.6
NumPy: 2.4.6

In [3]:
RAW_PATH = "../data/raw/ehr_encounters.csv"

df = pd.read_csv(RAW_PATH)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 4177
Columns: 102

In [4]:
pd.set_option("display.max_rows", 150)

df.columns.tolist()

['encounter_id',
 'patient_id',
 'encounter_date',
 'encounter_type',
 'discharge_date',
 'los_days',
 'dx_primary',
 'hcc_flag',
 'n_secondary_dx',
 'n_medications',
 'polypharmacy_flag',
 'note_type',
 'note_word_count',
 'facility_type',
 'facility_npi',
 'attending_npi',
 'fhir_bundle_path',
 'vs_hr_bpm',
 'vs_sbp_mmhg',
 'vs_dbp_mmhg',
 'vs_rr_breaths_min',
 'vs_temp_f',
 'vs_spo2_pct',
 'vs_weight_kg',
 'vs_height_cm',
 'vs_bmi',
 'lab_sodium',
 'lab_sodium_flag',
 'lab_potassium',
 'lab_potassium_flag',
 'lab_chloride',
 'lab_chloride_flag',
 'lab_bicarbonate_co2',
 'lab_bicarbonate_co2_flag',
 'lab_bun',
 'lab_bun_flag',
 'lab_creatinine',
 'lab_creatinine_flag',
 'lab_glucose',
 'lab_glucose_flag',
 'lab_calcium',
 'lab_calcium_flag',
 'lab_alt',
 'lab_alt_flag',
 'lab_ast',
 'lab_ast_flag',
 'lab_alp',
 'lab_alp_flag',
 'lab_total_bilirubin',
 'lab_total_bilirubin_flag',
 'lab_albumin',
 'lab_albumin_flag',
 'lab_wbc',
 'lab_wbc_flag',
 'lab_rbc',
 'lab_rbc_flag',
 'lab_hemoglobin',
 'lab_hemoglobin_flag',
 'lab_hematocrit',
 'lab_hematocrit_flag',
 'lab_mcv',
 'lab_mcv_flag',
 'lab_platelets',
 'lab_platelets_flag',
 'lab_ldl',
 'lab_ldl_flag',
 'lab_hdl',
 'lab_hdl_flag',
 'lab_total_cholesterol',
 'lab_total_cholesterol_flag',
 'lab_triglycerides',
 'lab_triglycerides_flag',
 'lab_hba1c',
 'lab_hba1c_flag',
 'lab_tsh',
 'lab_tsh_flag',
 'lab_free_t4',
 'lab_free_t4_flag',
 'lab_pt_inr',
 'lab_pt_inr_flag',
 'lab_aptt',
 'lab_aptt_flag',
 'lab_egfr',
 'lab_egfr_flag',
 'lab_crp',
 'lab_crp_flag',
 'lab_esr',
 'lab_esr_flag',
 'lab_ferritin',
 'lab_ferritin_flag',
 'age',
 'age_band',
 'sex',
 'race_ethnicity',
 'insurance_type',
 'pcp_flag',
 'state',
 'dx_secondary_1',
 'dx_secondary_2',
 'dx_secondary_3',
 'dx_secondary_4',
 'dx_secondary_5']

In [5]:
df.head()

,encounter_id,patient_id,encounter_date,encounter_type,discharge_date,los_days,dx_primary,hcc_flag,n_secondary_dx,n_medications,...,sex,race_ethnicity,insurance_type,pcp_flag,state,dx_secondary_1,dx_secondary_2,dx_secondary_3,dx_secondary_4,dx_secondary_5
0,545a8301-103a-4df7-bae6-ef033cc97092,HLT002-0000001,2021-07-25,emergency,2021-07-25,0,J45.20,False,0,2,...,female,Black or African American,Commercial,False,GA,NaN,NaN,NaN,NaN,NaN
1,4706d33b-2f7b-4838-a7bf-bb05b90d2570,HLT002-0000001,2022-05-12,outpatient,2022-05-12,0,J45.20,False,0,2,...,female,Black or African American,Commercial,False,GA,NaN,NaN,NaN,NaN,NaN
2,079d12ad-4328-4023-89dd-c5d4f9521da7,HLT002-0000001,2023-04-30,emergency,2023-04-30,0,J45.20,False,0,2,...,female,Black or African American,Commercial,False,GA,NaN,NaN,NaN,NaN,NaN
3,42b40aa5-5eb4-48af-8607-97385f5da23e,HLT002-0000001,2023-07-12,outpatient,2023-07-12,0,J45.20,False,0,2,...,female,Black or African American,Commercial,False,GA,NaN,NaN,NaN,NaN,NaN
4,6c6589ec-4464-4fcb-851a-8e71e5707a3d,HLT002-0000001,2023-11-26,outpatient,2023-11-26,0,J45.20,False,0,2,...,female,Black or African American,Commercial,False,GA,NaN,NaN,NaN,NaN,NaN

In [6]:
df.tail()

,encounter_id,patient_id,encounter_date,encounter_type,discharge_date,los_days,dx_primary,hcc_flag,n_secondary_dx,n_medications,...,sex,race_ethnicity,insurance_type,pcp_flag,state,dx_secondary_1,dx_secondary_2,dx_secondary_3,dx_secondary_4,dx_secondary_5
4172,ebbe2a4b-f08f-453f-910f-b0ebbeb32622,HLT002-0000500,2023-03-06,lab_only,2023-03-06,0,Z87.891,False,5,3,...,male,White,Dual-eligible,True,CA,Z79.4,I50.9,I48.91,E11.65,B20
4173,8cbc356f-5387-4e21-ba7c-87dfdb72616e,HLT002-0000500,2023-09-04,lab_only,2023-09-04,0,Z87.891,False,5,3,...,male,White,Dual-eligible,True,CA,Z79.4,I50.9,I48.91,E11.65,B20
4174,5a59ea41-2ff8-45ae-8550-dde0f5f1cf6c,HLT002-0000500,2023-10-31,inpatient,2023-11-06,6,Z87.891,False,5,3,...,male,White,Dual-eligible,True,CA,Z79.4,I50.9,I48.91,E11.65,B20
4175,bcb24aea-f7ea-4460-a835-f8f96b85418a,HLT002-0000500,2024-02-20,outpatient,2024-02-20,0,Z87.891,False,5,3,...,male,White,Dual-eligible,True,CA,Z79.4,I50.9,I48.91,E11.65,B20
4176,ac4e556b-b3a1-4ed0-9c3a-5fff1d71428a,HLT002-0000500,2024-11-22,lab_only,2024-11-22,0,Z87.891,False,5,3,...,male,White,Dual-eligible,True,CA,Z79.4,I50.9,I48.91,E11.65,B20

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Columns: 102 entries, encounter_id to dx_secondary_5
dtypes: bool(3), float64(42), int64(7), str(50)
memory usage: 3.2 MB

In [8]:
missing = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
)

missing[missing > 0]

fhir_bundle_path    4177
dx_secondary_5      3756
dx_secondary_4      3228
dx_secondary_3      2634
dx_secondary_2      1918
dx_secondary_1       954
dtype: int64

In [9]:
print("Total rows:", len(df))
print("Duplicate rows:", df.duplicated().sum())

Total rows: 4177
Duplicate rows: 0

In [10]:
df.shape

(4177, 102)

In [11]:
df.columns.tolist()

['encounter_id',
 'patient_id',
 'encounter_date',
 'encounter_type',
 'discharge_date',
 'los_days',
 'dx_primary',
 'hcc_flag',
 'n_secondary_dx',
 'n_medications',
 'polypharmacy_flag',
 'note_type',
 'note_word_count',
 'facility_type',
 'facility_npi',
 'attending_npi',
 'fhir_bundle_path',
 'vs_hr_bpm',
 'vs_sbp_mmhg',
 'vs_dbp_mmhg',
 'vs_rr_breaths_min',
 'vs_temp_f',
 'vs_spo2_pct',
 'vs_weight_kg',
 'vs_height_cm',
 'vs_bmi',
 'lab_sodium',
 'lab_sodium_flag',
 'lab_potassium',
 'lab_potassium_flag',
 'lab_chloride',
 'lab_chloride_flag',
 'lab_bicarbonate_co2',
 'lab_bicarbonate_co2_flag',
 'lab_bun',
 'lab_bun_flag',
 'lab_creatinine',
 'lab_creatinine_flag',
 'lab_glucose',
 'lab_glucose_flag',
 'lab_calcium',
 'lab_calcium_flag',
 'lab_alt',
 'lab_alt_flag',
 'lab_ast',
 'lab_ast_flag',
 'lab_alp',
 'lab_alp_flag',
 'lab_total_bilirubin',
 'lab_total_bilirubin_flag',
 'lab_albumin',
 'lab_albumin_flag',
 'lab_wbc',
 'lab_wbc_flag',
 'lab_rbc',
 'lab_rbc_flag',
 'lab_hemoglobin',
 'lab_hemoglobin_flag',
 'lab_hematocrit',
 'lab_hematocrit_flag',
 'lab_mcv',
 'lab_mcv_flag',
 'lab_platelets',
 'lab_platelets_flag',
 'lab_ldl',
 'lab_ldl_flag',
 'lab_hdl',
 'lab_hdl_flag',
 'lab_total_cholesterol',
 'lab_total_cholesterol_flag',
 'lab_triglycerides',
 'lab_triglycerides_flag',
 'lab_hba1c',
 'lab_hba1c_flag',
 'lab_tsh',
 'lab_tsh_flag',
 'lab_free_t4',
 'lab_free_t4_flag',
 'lab_pt_inr',
 'lab_pt_inr_flag',
 'lab_aptt',
 'lab_aptt_flag',
 'lab_egfr',
 'lab_egfr_flag',
 'lab_crp',
 'lab_crp_flag',
 'lab_esr',
 'lab_esr_flag',
 'lab_ferritin',
 'lab_ferritin_flag',
 'age',
 'age_band',
 'sex',
 'race_ethnicity',
 'insurance_type',
 'pcp_flag',
 'state',
 'dx_secondary_1',
 'dx_secondary_2',
 'dx_secondary_3',
 'dx_secondary_4',
 'dx_secondary_5']

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Columns: 102 entries, encounter_id to dx_secondary_5
dtypes: bool(3), float64(42), int64(7), str(50)
memory usage: 3.2 MB

In [13]:
missing = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
)

missing[missing > 0]

fhir_bundle_path    4177
dx_secondary_5      3756
dx_secondary_4      3228
dx_secondary_3      2634
dx_secondary_2      1918
dx_secondary_1       954
dtype: int64

In [15]:
print("Total rows:", len(df))
print("Duplicate rows:", df.duplicated().sum())
print(
    "Duplicate encounter IDs:",
    df["encounter_id"].duplicated().sum()
)
print(
    "Duplicate patient IDs:",
    df["patient_id"].duplicated().sum()
)

Total rows: 4177
Duplicate rows: 0
Duplicate encounter IDs: 0
Duplicate patient IDs: 3677

In [16]:
df["encounter_date"] = pd.to_datetime(
    df["encounter_date"],
    errors="coerce"
)

df["discharge_date"] = pd.to_datetime(
    df["discharge_date"],
    errors="coerce"
)

print("Invalid encounter dates:", df["encounter_date"].isna().sum())
print("Invalid discharge dates:", df["discharge_date"].isna().sum())

Invalid encounter dates: 0
Invalid discharge dates: 0

In [17]:
print("Encounter start:", df["encounter_date"].min())
print("Encounter end:", df["encounter_date"].max())

Encounter start: 2020-01-02 00:00:00
Encounter end: 2024-12-31 00:00:00

In [18]:
calculated_los = (
    df["discharge_date"] - df["encounter_date"]
).dt.days

In [19]:
los_check = pd.DataFrame({
    "reported_los": df["los_days"],
    "calculated_los": calculated_los
})

los_check["difference"] = (
    los_check["reported_los"] -
    los_check["calculated_los"]
)

los_check["difference"].value_counts(dropna=False).head(20)

difference
0    4177
Name: count, dtype: int64

In [20]:
categorical_columns = [
    "encounter_type",
    "facility_type",
    "note_type",
    "age_band",
    "sex",
    "race_ethnicity",
    "insurance_type",
    "state"
]

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False).head(20))

--- encounter_type ---
encounter_type
outpatient    2286
emergency      638
inpatient      612
telehealth     429
lab_only       212
Name: count, dtype: int64

--- facility_type ---
facility_type
FQHC           892
Urgent Care    846
Clinic         819
ASC            812
Hospital       808
Name: count, dtype: int64

--- note_type ---
note_type
SOAP         3048
Discharge     612
Radiology     517
Name: count, dtype: int64

--- age_band ---
age_band
35-49    875
18-34    804
75+      796
50-64    744
65-74    626
0-17     332
Name: count, dtype: int64

--- sex ---
sex
male      2314
female    1803
other       60
Name: count, dtype: int64

--- race_ethnicity ---
race_ethnicity
White                        2359
Hispanic or Latino            756
Black or African American     661
Asian                         314
Two or More Races              46
AIAN                           36
NHOPI                           5
Name: count, dtype: int64

--- insurance_type ---
insurance_type
Medicare         1720
Commercial       1520
Medicaid          514
Dual-eligible     256
Uninsured         167
Name: count, dtype: int64

--- state ---
state
NY    492
FL    479
CA    461
MI    457
TX    452
NC    441
OH    392
IL    362
GA    325
PA    316
Name: count, dtype: int64

In [24]:
## 2. Data Quality Profiling

# Before transforming the healthcare dataset, we first profile the raw
# data to understand its quality.

# The profiling stage checks:

# - Missing values
# - Duplicate records
# - Duplicate encounter identifiers
# - Date validity
# - Length-of-stay consistency
# - Categorical values
# - Numeric distributions

# No records are modified or deleted during this stage. The purpose is
# to identify data-quality issues before defining the cleaning rules.

In [25]:
# ### 2.1 Missing Value Analysis

# Missing values are common in healthcare datasets because not every
# measurement or field is available for every encounter.

# We calculate both the number and percentage of missing values for
# each column. This helps determine which fields require validation or
# special handling during the ingestion process.

In [26]:
# Calculate missing values for every column
missing = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percentage": (df.isna().mean() * 100).round(2)
})

# Keep only columns that contain missing values
missing = (
    missing[missing["missing_count"] > 0]
    .sort_values("missing_percentage", ascending=False)
)

missing

                  missing_count  missing_percentage
fhir_bundle_path           4177              100.00
dx_secondary_5             3756               89.92
dx_secondary_4             3228               77.28
dx_secondary_3             2634               63.06
dx_secondary_2             1918               45.92
dx_secondary_1              954               22.84

In [27]:
# Display the 20 columns with the highest percentage of missing values
missing.head(20)

                  missing_count  missing_percentage
fhir_bundle_path           4177              100.00
dx_secondary_5             3756               89.92
dx_secondary_4             3228               77.28
dx_secondary_3             2634               63.06
dx_secondary_2             1918               45.92
dx_secondary_1              954               22.84

In [28]:
# ### 2.2 Duplicate Record Analysis

# Duplicate records can cause incorrect analytical results, such as
# inflated encounter counts.

# We therefore check:

# 1. Completely duplicated rows
# 2. Duplicate encounter IDs
# 3. Duplicate patient IDs

# A patient ID is expected to appear multiple times because a patient
# may have multiple healthcare encounters. Therefore, duplicate patient
# IDs are not automatically considered an error.

In [31]:
# Count completely duplicated rows
duplicate_rows = df.duplicated().sum()

# Count duplicate encounter IDs
duplicate_encounters = df["encounter_id"].duplicated().sum()

# Count duplicate patient IDs
duplicate_patients = df["patient_id"].duplicated().sum()

print(f"Total records: {len(df):,}")
print(f"Duplicate rows: {duplicate_rows:,}")
print(f"Duplicate encounter IDs: {duplicate_encounters:,}")
print(f"Duplicate patient IDs: {duplicate_patients:,}")


# A patient can legitimately have multiple encounters. Therefore,
# `patient_id` should not be unique in the encounter-level dataset.

# The expected business grain for the future fact table is:

# **One row = one healthcare encounter.**

# Therefore, `encounter_id` is more appropriate as the uniqueness check
# for the encounter fact table.

Total records: 4,177
Duplicate rows: 0
Duplicate encounter IDs: 0
Duplicate patient IDs: 3,677

In [32]:
# ### 2.3 Date Validation

# The dataset contains encounter and discharge dates.

# We convert these columns to pandas datetime values using
# `errors="coerce"` so that invalid date values become null instead of
# causing the pipeline to fail unexpectedly.

# We then inspect the number of invalid dates and the overall date range.

In [33]:
# Convert date columns to datetime
df["encounter_date"] = pd.to_datetime(
    df["encounter_date"],
    errors="coerce"
)

df["discharge_date"] = pd.to_datetime(
    df["discharge_date"],
    errors="coerce"
)

# Count invalid/missing dates
invalid_encounter_dates = df["encounter_date"].isna().sum()
invalid_discharge_dates = df["discharge_date"].isna().sum()

print(f"Invalid encounter dates: {invalid_encounter_dates:,}")
print(f"Invalid discharge dates: {invalid_discharge_dates:,}")

Invalid encounter dates: 0
Invalid discharge dates: 0

In [34]:
# Inspect the date range
print("Earliest encounter:", df["encounter_date"].min())
print("Latest encounter:", df["encounter_date"].max())

print("Earliest discharge:", df["discharge_date"].min())
print("Latest discharge:", df["discharge_date"].max())

Earliest encounter: 2020-01-02 00:00:00
Latest encounter: 2024-12-31 00:00:00
Earliest discharge: 2020-01-02 00:00:00
Latest discharge: 2024-12-31 00:00:00

In [35]:
# ### 2.4 Encounter and Discharge Date Consistency

# We check whether discharge dates occur before encounter dates.

# A discharge date earlier than the encounter date would indicate a
# potential data-quality issue.

# This check does not modify the source data. It only identifies records
# that require investigation.

In [36]:
# Identify records where discharge occurs before the encounter
invalid_date_order = df[
    df["discharge_date"].notna()
    & df["encounter_date"].notna()
    & (df["discharge_date"] < df["encounter_date"])
]

print("Records with discharge before encounter:",
      len(invalid_date_order))

Records with discharge before encounter: 0

In [37]:
# ### 2.5 Length-of-Stay Validation

# The dataset contains a reported `los_days` value as well as encounter
# and discharge dates.

# We calculate an independent length of stay from the two dates and
# compare it with the reported value.

# This provides an example of a cross-field data-quality validation.

In [38]:
# Calculate length of stay from the encounter and discharge dates
calculated_los = (
    df["discharge_date"] - df["encounter_date"]
).dt.days

# Compare calculated and reported values
los_comparison = pd.DataFrame({
    "reported_los": df["los_days"],
    "calculated_los": calculated_los
})

los_comparison["difference"] = (
    los_comparison["reported_los"]
    - los_comparison["calculated_los"]
)

los_comparison.head()

   reported_los  calculated_los  difference
0             0               0           0
1             0               0           0
2             0               0           0
3             0               0           0
4             0               0           0

In [39]:
# Count records where reported and calculated LOS differ
los_mismatch = los_comparison[
    los_comparison["reported_los"].notna()
    & los_comparison["calculated_los"].notna()
    & (los_comparison["difference"] != 0)
]

print("Records with LOS mismatch:", len(los_mismatch))

Records with LOS mismatch: 0

In [40]:
# ### 2.6 Categorical Value Analysis

# Categorical fields should contain standardized values.

# We inspect the unique value distributions of important categorical
# columns before defining accepted values or normalization rules.

# These results will later help us implement data-quality tests in dbt.

In [41]:
categorical_columns = [
    "encounter_type",
    "facility_type",
    "note_type",
    "age_band",
    "sex",
    "race_ethnicity",
    "insurance_type",
    "state"
]

for column in categorical_columns:
    print(f"\n{'=' * 60}")
    print(f"{column}")
    print(f"{'=' * 60}")
    print(df[column].value_counts(dropna=False).head(20))

============================================================
encounter_type
============================================================
encounter_type
outpatient    2286
emergency      638
inpatient      612
telehealth     429
lab_only       212
Name: count, dtype: int64

============================================================
facility_type
============================================================
facility_type
FQHC           892
Urgent Care    846
Clinic         819
ASC            812
Hospital       808
Name: count, dtype: int64

============================================================
note_type
============================================================
note_type
SOAP         3048
Discharge     612
Radiology     517
Name: count, dtype: int64

============================================================
age_band
============================================================
age_band
35-49    875
18-34    804
75+      796
50-64    744
65-74    626
0-17     332
Name: count, dtype: int64

============================================================
sex
============================================================
sex
male      2314
female    1803
other       60
Name: count, dtype: int64

============================================================
race_ethnicity
============================================================
race_ethnicity
White                        2359
Hispanic or Latino            756
Black or African American     661
Asian                         314
Two or More Races              46
AIAN                           36
NHOPI                           5
Name: count, dtype: int64

============================================================
insurance_type
============================================================
insurance_type
Medicare         1720
Commercial       1520
Medicaid          514
Dual-eligible     256
Uninsured         167
Name: count, dtype: int64

============================================================
state
============================================================
state
NY    492
FL    479
CA    461
MI    457
TX    452
NC    441
OH    392
IL    362
GA    325
PA    316
Name: count, dtype: int64

In [42]:
# ### 2.7 Numeric Data Profiling

# Numeric healthcare fields are profiled to identify missing values,
# unexpected ranges, and unusual distributions.

# At this stage, the values are only being profiled. We are not making
# clinical conclusions from the measurements.

In [43]:
numeric_columns = [
    "age",
    "los_days",
    "n_secondary_dx",
    "n_medications",
    "note_word_count",
    "vs_hr_bpm",
    "vs_sbp_mmhg",
    "vs_dbp_mmhg",
    "vs_rr_breaths_min",
    "vs_temp_f",
    "vs_spo2_pct",
    "vs_weight_kg",
    "vs_height_cm",
    "vs_bmi",
    "lab_glucose",
    "lab_creatinine",
    "lab_wbc",
    "lab_hba1c"
]

numeric_profile = df[numeric_columns].describe().T

numeric_profile

,count,mean,std,min,25%,50%,75%,max
age,4177.0,51.323677,24.160296,1.00,32.00,51.00,70.00,94.00
los_days,4177.0,0.822839,2.146173,0.00,0.00,0.00,0.00,13.00
n_secondary_dx,4177.0,2.009816,1.643124,0.00,1.00,2.00,3.00,5.00
n_medications,4177.0,3.503711,1.829554,0.00,2.00,3.00,5.00,8.00
note_word_count,4177.0,171.057458,42.894892,51.00,177.00,186.00,193.00,212.00
vs_hr_bpm,4177.0,79.001628,14.928594,40.00,68.60,77.90,88.30,139.80
vs_sbp_mmhg,4177.0,133.773043,21.707096,70.00,119.00,133.00,149.00,218.00
vs_dbp_mmhg,4177.0,84.689011,12.341262,40.00,76.00,84.00,93.00,134.00
vs_rr_breaths_min,4177.0,17.284798,3.878067,8.00,14.70,16.90,19.60,31.90
vs_temp_f,4177.0,99.109480,1.350871,95.70,98.20,98.90,99.70,105.10
vs_spo2_pct,4177.0,95.777975,2.740964,82.50,94.60,96.30,97.70,100.00
vs_weight_kg,4177.0,83.405913,18.623061,30.00,70.30,82.80,95.30,154.00
vs_height_cm,4177.0,167.573929,9.986075,136.00,160.70,167.60,174.50,203.90
vs_bmi,4177.0,29.599617,5.578545,10.20,25.90,29.50,33.30,49.50
lab_glucose,4177.0,110.930996,42.769836,21.00,83.51,88.23,137.69,289.04
lab_creatinine,4177.0,1.119210,0.530977,0.20,0.85,0.93,1.04,4.38
lab_wbc,4177.0,7.508219,1.178077,3.24,6.71,7.50,8.32,13.34
lab_hba1c,4177.0,6.015758,1.857047,3.33,4.75,5.05,7.34,13.22

In [44]:
# ### 2.8 Data Quality Summary

# The following summary provides a high-level view of the raw dataset,
# including row count, column count, duplicate records, and missing
# values.

# This profile will be used to define the validation and cleaning rules
# implemented in the Python ingestion pipeline.

In [45]:
quality_summary = pd.DataFrame({
    "metric": [
        "Total rows",
        "Total columns",
        "Duplicate rows",
        "Duplicate encounter IDs",
        "Duplicate patient IDs",
        "Invalid encounter dates",
        "Invalid discharge dates",
        "Discharge before encounter",
        "Columns with missing values"
    ],
    "value": [
        len(df),
        len(df.columns),
        duplicate_rows,
        duplicate_encounters,
        duplicate_patients,
        invalid_encounter_dates,
        invalid_discharge_dates,
        len(invalid_date_order),
        len(missing)
    ]
})

quality_summary

                        metric  value
0                   Total rows   4177
1                Total columns    102
2               Duplicate rows      0
3      Duplicate encounter IDs      0
4        Duplicate patient IDs   3677
5      Invalid encounter dates      0
6      Invalid discharge dates      0
7   Discharge before encounter      0
8  Columns with missing values      6

In [46]:
# ### 2.9 Save Data-Quality Profiles

# The profiling results are saved separately from the raw dataset.

# The raw source file remains unchanged, while generated profiling
# artifacts are stored in the processed-data directory.

In [47]:
# Save missing-value profile
missing.to_csv(
    "../data/processed/missing_value_profile.csv"
)

# Save numeric profile
numeric_profile.to_csv(
    "../data/processed/numeric_profile.csv"
)

# Save overall quality summary
quality_summary.to_csv(
    "../data/processed/data_quality_summary.csv",
    index=False
)

print("Data-quality profiles saved successfully.")

Data-quality profiles saved successfully.

In [48]:
print("Duplicate encounter IDs:", df["encounter_id"].duplicated().sum())
print("Missing encounter IDs:", df["encounter_id"].isna().sum())
print("Missing patient IDs:", df["patient_id"].isna().sum())
print("Missing encounter dates:", df["encounter_date"].isna().sum())

Duplicate encounter IDs: 0
Missing encounter IDs: 0
Missing patient IDs: 0
Missing encounter dates: 0